###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################
homeassistant:
  name: Home Assistant
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # elevation: !secret evelation_loc_home
  time_zone: America/New_York
  temperature_unit: F
  unit_system: metric
  customize: !include includes/customize.yaml

###################################################
#                                                 #
#                     Panel                       #
#                                                 #
################################################### 
panel_iframe:
  windguru:
    title: 'Windguru'
    url: 'https://www.windguru.cz/784224'
    icon: mdi:weather-windy

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
http:
  api_password: !secret http_api_password # Used for IOS App
  # Using proxy ssl_certificate: !secret http_ssl_certificate
  # Using Proxy ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.10
discovery:
  enable:
    - dlna_dmr
config:
ios:
map:
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
# Enables support for tracking state changes over time
history:
# View all events in a logbook
logbook:
device_tracker:
  - platform: nmap_tracker
    hosts: 10.0.0.0/24
    home_interval: 10
    exclude:
     - 10.0.0.2

####################################################
#                                                  #
#                 Customisations                   #
#                                                  #
####################################################
frontend:
  javascript_version: auto
  themes: !include includes/themes.yaml

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################
logger:
  default: warn

####################################################
#                                                  #
#                      Cloud                       #
#                                                  #
####################################################
#cloud:
  # Home Assistant Cloud allows use of the Alexa Skill

####################################################
#                                                  #
#                     Camera                       #
#                                                  #
####################################################


####################################################
#                                                  #
#            Heating, Cooling & Security           #
#                                                  #
####################################################


####################################################
#                                                  #
#            RFXtrx433 & Z-Wave Devices            #
#                                                  #
####################################################


####################################################
#                                                  #
#                   Emulated Hue                   #
#                                                  #
####################################################
emulated_hue:
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene

####################################################
#                                                  #
#                 Push Notifications               #
#                                                  #
####################################################



####################################################
#                                                  #
#                      Pushover                    #
#                                                  #
####################################################

# Pushover
notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################
mqtt:
  broker: core-mosquitto
  username: !secret MQTT_username
  password: !secret MQTT_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

####################################################
#                                                  #
#                Climate & Weather                 #
#                                                  #
####################################################
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    units: us
sun:

####################################################
#                                                  #
#                  Text to Speech                  #
#                                                  #
####################################################
# tts:
#   - platform: google
#     cache: true
#     cache_dir: /tmp/tts
#     time_memory: 300
#   - platform: voicerss
#     api_key: !secret voicerss_api_key
#     language: 'en-gb'
#     format: '44khz_16bit_stereo'

####################################################
#                                                  #
#                      Timers                      #
#                                                  #
####################################################


####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
automation: !include includes/automations.yaml
group: !include includes/groups.yaml
history: !include includes/history.yaml
light: !include includes/lights.yaml
logbook: !include includes/logbook.yaml
recorder: !include includes/recorder.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml

####################################################
