###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################
homeassistant:
  name: Home Assistant
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  # elevation: !secret evelation_loc_home
  time_zone: America/New_York
  temperature_unit: F
  unit_system: metric
  customize: !include includes/customize.yaml
  customize_glob: !include includes/customize_glob.elevationyaml

###################################################
#                                                 #
#                     Panel                       #
#                                                 #
################################################### 
panel_iframe:
  windguru:
    title: 'Windguru'
    url: 'https://www.windguru.cz/784224'
    icon: mdi:weather-windy

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
http:
  api_password: !secret http_api_password # Used for IOS App
  # Using proxy ssl_certificate: !secret http_ssl_certificate
  # Using Proxy ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
discovery:
  ignore:
  include_used_components: True
config:
ios:
map:

####################################################
#                                                  #
#                 Customisations                   #
#                                                  #
####################################################
frontend:
  javascript_version: auto
  themes: !include includes/themes.yaml

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################
logger:
  default: warn
  logs:
    homeassistant.components.dyson: info
  #   homeassistant.components.mqtt: debug
  # #   homeassistant.components.light: info
  #   homeassistant.components.dyson: debug
  #   homeassistant.components.sensor.dyson: debug
  #   homeassistant.components.fan.dyson: debug

####################################################
#                                                  #
#                      Cloud                       #
#                                                  #
####################################################
#cloud:
  # Home Assistant Cloud allows use of the Alexa Skill

####################################################
#                                                  #
#                     Camera                       #
#                                                  #
####################################################


####################################################
#                                                  #
#            Heating, Cooling & Security           #
#                                                  #
####################################################


####################################################
#                                                  #
#            RFXtrx433 & Z-Wave Devices            #
#                                                  #
####################################################


####################################################
#                                                  #
#                   Emulated Hue                   #
#                                                  #
####################################################
emulated_hue:
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene

####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################
mqtt:
  broker: core-mosquitto
  username: !secret MQTT_username
  password: !secret MQTT_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

####################################################
#                                                  #
#                Climate & Weather                 #
#                                                  #
####################################################
weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    units: us
sun:

####################################################
#                                                  #
#                  Text to Speech                  #
#                                                  #
####################################################
# tts:
#   - platform: google
#     cache: true
#     cache_dir: /tmp/tts
#     time_memory: 300
#   - platform: voicerss
#     api_key: !secret voicerss_api_key
#     language: 'en-gb'
#     format: '44khz_16bit_stereo'

####################################################
#                                                  #
#                      Timers                      #
#                                                  #
####################################################


####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
automation: !include includes/automations.yaml
group: !include includes/groups.yaml
history: !include includes/history.yaml
light: !include includes/lights.yaml
logbook: !include includes/logbook.yaml
recorder: !include includes/recorder.yaml
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switches.yaml
zone: !include includes/zones.yaml

####################################################
