title: Lovelace UI (Alpha)
###############################
#         Custom Cards        #
###############################
# resources:
#   - url: /local/lovelace/custom-cards/state-attribute-element.js?v=0
#     type: js

views:
###############################
#       Main View (Home)      #
###############################
  - title: Home
    icon: mdi:home
    cards:
### STACK: Column 1
      - type: vertical-stack
        cards:
        - type: picture-glance
          title: Living Room
          image: /local/lovelace/living_room.png
          entities:
            - light.hue_lamp_2
            - light.door
            - light.bookshelf

###############################
#     Windguru Panel View     #
###############################
  - title: Sailing
    icon: mdi:weather-windy
    panel: true
    cards:
    - type: iframe
      url: 'https://www.windguru.cz/784224'
      # aspect_ratio: 500%

###############################
#        Original Home        #
###############################
  - title: Home
    cards:
      - type: entities
        title: Living Room Lights
        entities:
          - light.hue_lamp_2
          - light.door
          - light.bookshelf
      - type: entities
        title: Scenes Living Room
        entities:
          - scene.bright
          - scene.comfortable
          - scene.movie
      - type: entities
        title: Weather (local)
        entities:
          - sun.sun
          - sensor.moon
      - type: entities
        title: Waze Journeys
        entities:
          - sensor.to_home
          - sensor.to_work
      - type: entity-filter
        entities:
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home



###############################
#         Living Room         #
###############################
  - title: Living Room
    cards:
      - type: entities
        title: Living Room Lights
        entities:
          - light.hue_lamp_2
          - light.door
          - light.bookshelf
      - type: entities
        title: Scenes Living Room
        entities:
          - scene.bright
          - scene.comfortable
          - scene.movie


###############################
#           Outside           #
###############################
  - title: Outside
    cards:
      - type: glance
        show_name: true
        entities:
          - sensor.temp_humid_ext_1_temperature
          - sensor.temp_humid_ext_1_humidity
      - type: entities
        title: Weather (local)
        entities:
          - sun.sun
          - sensor.moon
      - type: weather-forecast
        entity: weather.yweather


###############################
#            Family           #
###############################
  # - title: Family
  #   icon: mdi:account-multiple
  #   cards:
  #     - type: entities
  #       title: Tracked Devices
  #       entities:
  #         - device_tracker.martins_iphone
  #         - sensor.martins_iphone_battery_level
  #         - sensor.martins_iphone_battery_state
  #         - device_tracker.michelles_iphone
  #         - sensor.iphone_battery_level
  #         - sensor.iphone_battery_state
  #     - type: entities
  #       title: HaveIBeenPwned
  #       entities:
  #         - sensor.breaches_martinrowannetcouk
  #         - sensor.breaches_michellerowannetcouk
  #         - sensor.breaches_junerowannetcouk
  #         - sensor.breaches_morganrowannetcouk
  #         - sensor.breaches_fraserrowannetcouk
  #         - sensor.breaches_robertrowannetcouk
  #         - sensor.breaches_martinrowancitrixcom
  #         - sensor.breaches_martinrowaneucitrixcom
  #         - sensor.breaches_mrowanhighlightnet

###############################
#            Systems          #
###############################
  - title: Systems
    icon: mdi:server-network
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Internet
            entities:
              - entity: sensor.speedtest_ping
                name: Ping
              - entity: sensor.speedtest_download
                name: Download
              - entity: sensor.speedtest_upload
                name: Upload
          - type: history-graph
            entities:
              - entity: sensor.speedtest_download
                name: Download
              - entity: sensor.speedtest_upload
                name: Upload
          - type: picture-entity
            entity: camera.broadbandquality
      - type: vertical-stack
        cards:
          - type: glance
            title: Hass.io Raspberry Pi
            entities:
              - entity: sensor.processor_use
                name: '% CPU'
              - entity: sensor.memory_free
                name: Mem Free
              - entity: sensor.memory_use_percent
                name: '% Mem Used'
          - type: glance
            entities:
              - entity: sensor.disk_free_
                name: Disk Free
              - entity: sensor.disk_use_percent_
                name: '% Disk Used'
              - entity: sensor.swap_use_percent
                name: '% Swap Used'
          - type: glance
            entities:
              - entity: sensor.load_1m
                name: 1m
              - entity: sensor.load_5m
                name: 5m
              - entity: sensor.load_15m
                name: 15m
      - type: entities
        title: HaveIBeenPwned
        entities:
          - !secret sensor_hibp_email1
          - !secret sensor_hibp_email2

###############################
#          Automation         #
###############################
  - title: Automation
    icon: mdi:home-automation
    cards:
      - type: entities
        title: Utilities
        entities:
          - automation.update_config_hass_if_travis_build_is_successfull
          - automation.have_i_been_pwned_change
          - automation.hass_update_available_notifications
          - automation.hassio_weekly_snapshot_3am
          - automation.dropbox_snapshot_sync_4am
      - type: entities
        title: HAPi Resource Monitoring
        entities:
          - automation.hapi_high_load_alert
          - automation.hapi_low_disk_space_alert
          - automation.hapi_low_memory_alert
      - type: entities
        title: Power Control
        entities:
          - automation.turn_on_lights_in_the_morning_and_at_sunset
          - automation.turn_off_morning_lights
### Auto generated by python-lovelace migration tool. Doesn't work on 0.74.0
  # - title: All Entities
  #   tab_icon: mdi:settings
  #   cards:
  #     - type: entity-filter
  #       filter:
  #         - {}
  #       card_config:
  #         title: All Entities
