- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.jazinheirahome_assistant_config_last_build_id
  condition:
    - condition: state
      entity_id: sensor.jazinheirahome_assistant_config_last_build_state
      state: 'passed'
  action:
    - service: hassio.addon_stop # Requires Git Pull is set to auto-start
      data: 
        addon: "core_git_pull"
    - delay: 0:01
    - service: hassio.addon_start
      data: 
        addon: "core_git_pull"

- id: a_hapi_low_disk
  alias: HAPi Low Disk Space Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 90
  action:
    - service: notify.pushover
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Disk Space > 90% Used"

- id: a_hapi_low_mem
  alias: HAPi Low Memory Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.memory_use_percent
      above: 90
  action:
    - service: notify.pushover
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Memory > 90% Used"

- id: a_hapi_high_load
  alias: HAPi High Load Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.load_5m
      above: 2.8 # 4 Cores in RPi3 x 0.7 per core, for relatively high sustained load = 
  action:
    - service: notify.pushover
      data: 
        title: "HAPi Low Resource Alert"
        message: "System Load 5m Load Average > 2.8"

- id: a_haveibeenpwned_change
  alias: Have I Been Pwned Change
  trigger:
    - platform: numeric_state
      above: 0
      entity_id: 
        - !secret sensor_hibp_email1
        - !secret sensor_hibp_email2
  action:
    service: notify.pushover
    data_template:
      message: "Warning - HaveIbeenPwned detected {{trigger.to_state.attributes.friendly_name}}"


- id: a_hass_update_available
  alias: 'HASS Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.pushover
    data:
      message: 'Update for Home Assistant is available.'