- id: a_config_update
  alias: Update config HASS if travis build is successfull
  trigger:
    - platform: state
      entity_id: sensor.jazinheirahome_assistant_config_last_build_id
  condition:
    - condition: state
      entity_id: sensor.jazinheirahome_assistant_config_last_build_state
      state: 'passed'
  action:
    - service: hassio.addon_stop # Requires Git Pull is set to auto-start
      data: 
        addon: "core_git_pull"
    - delay: 0:01
    - service: hassio.addon_start
      data: 
        addon: "core_git_pull"

- id: a_hapi_low_disk
  alias: HAPi Low Disk Space Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 90
  action:
    - service: notify.pushover
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Disk Space > 90% Used"

- id: a_hapi_low_mem
  alias: HAPi Low Memory Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.memory_use_percent
      above: 90
  action:
    - service: notify.pushover
      data: 
        title: "HAPi Low Resource Alert"
        message: "Low Memory > 90% Used"

- id: a_hapi_high_load
  alias: HAPi High Load Alert
  trigger:
    - platform: numeric_state
      entity_id: sensor.load_5m
      above: 2.8 # 4 Cores in RPi3 x 0.7 per core, for relatively high sustained load = 
  action:
    - service: notify.pushover
      data: 
        title: "HAPi Low Resource Alert"
        message: "System Load 5m Load Average > 2.8"

- id: a_miner01_power_watch
  alias: Miner01 Power Watcher
  trigger:
    - platform: numeric_state
      entity_id: sensor.tp_hs110_9_power
      below: 1300
      for:
        minutes: 20
  action:
    - service: notify.pushover
      data_template:
        title: "Miner Monitor: Miner01 - Low Power"
        message: >-
          Usage - {{ states("sensor.tp_hs110_9_power") }} W, expected > 1300W, 

- id: a_miner01_lowpower_reboot
  alias: Miner01 Low Power Reboot
  trigger:
    - platform: numeric_state
      entity_id: sensor.tp_hs110_9_power
      below: 1300
      for:
        minutes: 30
  action:
    - service: notify.pushover
      data:
        title: "Miner Monitor: Miner01"
        message:
          Rebooting Miner01. Low power usage for > 30 mins.
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_9
    - delay: 0:01
    - service: notify.pushover
      data:
        title: "Miner Monitor: Miner01"
        message: "Powering Back On!"
    - service: homeassistant.turn_on
      entity_id: switch.tp_hs110_9

- id: a_haveibeenpwned_change
  alias: Have I Been Pwned Change
  trigger:
    - platform: numeric_state
      above: 0
      entity_id: 
        - !secret sensor_hibp_email3
        - !secret sensor_hibp_email4
        - !secret sensor_hibp_email5
        - !secret sensor_hibp_email9
    - platform: numeric_state
      above: 1
      entity_id:
        - !secret sensor_hibp_email2
    - platform: numeric_state
      above: 2
      entity_id:
        - !secret sensor_hibp_email6
        - !secret sensor_hibp_email7
    - platform: numeric_state
      above: 3
      entity_id:
        - !secret sensor_hibp_email8
    - platform: numeric_state
      above: 4
      entity_id:
        - !secret sensor_hibp_email1
  action:
    service: notify.pushover
    data_template:
      message: "Warning - HaveIbeenPwned detected {{trigger.to_state.attributes.friendly_name}}"

- id: a_sonos_tts_test
  alias: Sonos TTS Test
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.conservatory
        volume: 0.5
        message: 'This is a test of Sonos Text to Speech'
        # Delay needs to be long enough to allow text to be read aloud
        delay: '00:00:05'

- id: a_hass_update_available
  alias: 'HASS Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.pushover
    data:
      message: 'Update for Home Assistant is available.'

- id: a_sonos_burglar_alarm
  alias: Sonos Burglar Alarm
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_alarm
      data:
        # Maximum Volume
        volume: 1.0
        # Duration before stopping and restoring state
        delay: '00:01:00'

- id: a_sonos_restore_snapshot
  alias: 'Sonos restore snapshot state'
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: media_player.sonos_restore

- id: a_garage_Fan_On
  alias: Garage Fan Turn On When Hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_temperature_2
      above: 20
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_on
      entity_id: switch.tp_hs110_6

- id: a_garage_Fan_Off
  alias: Garage Fan Turn Off When Not Hot
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_zw100_multisensor_6_temperature_2
      below: 20
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tp_hs110_6

- id: a_weekly_snapshot
  alias: HASSIO Weekly Snapshot (3am)
  trigger:
    - platform: time
      at: '3:00:00'
  condition:
    condition: time
    weekday:
      - sun
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}

- id: a_weekly_snapshot_dropbox_sync
  alias: Dropbox Snapshot Sync (4am)
  trigger: 
    - platform: time
      at: '4:00:00'
  action:
    - service: hassio.addon_stdin
      data_template:
        addon: 7be23ff5_dropbox_sync
        input: {"command":"upload"}