#### Sensors.yaml ####

# Raspberry Pi System Information
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: disk_use_percent
      arg: /
    - type: swap_use_percent
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m

############################################################
#
#  Sensor Templates
#
############################################################

### Component to monitor travis-ci status of config file repro.
- platform: travisci
  api_key: !secret travisci_api_key
  # scan_interval: 60
  repository: "home_assistant_config"
  monitored_conditions:
    - last_build_id
    - last_build_state

### Component for HaveIBeenPwned Sensor
- platform: haveibeenpwned
  email:
    - !secret hibp_email1
    - !secret hibp_email2

### Waze Time Travel
- platform: waze_travel_time
  name: "To Work"
  origin: !secret waze_home
  destination: !secret waze_work
  region: 'US'

- platform: waze_travel_time
  name: "To Home"
  origin: !secret waze_work
  destination: !secret waze_home
  region: 'US'

### Speedtest.net
- platform: speedtest
  minute:
    - 0
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload